### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by supremelucifer** [watkins-matt/home-assistant-google-keep-sync#38] opened 2024-09-30 22:16 UTC
I was setting this integration up with a friend of mine. After i first generated a token for my friend it worked for him, after that i generated a different token with my mail and pass for myself, i integrated it and i keep on seeing his list. I thought it was the docker so i installed the docker again on a different machine with a new pass and token. But still i see his list, waited for 20 minutes to see if it is a sync problem but still his list.

**Comment by supremelucifer** [comment] 2024-09-30 23:24
Looked in the database, core.config_entries and these are all my entries. I really have no idea right now. Restarted, checked different browsers, uninstall, re install and all didnt work

**Comment by watkins-matt** [comment] 2024-10-01 01:11
So the token is basically the same as a password and gives you full access to an account. It sounds like you may have used your friend's token? 

You should be able to delete the integration and add it again with new credentials. To be safe, also delete the cached data before recreating. It should can be found at config/.storage/google_keep_sync.your.email@domain.com.json. 

So
1. Delete the Google Keep Sync integration data.
2. Delete the config/.storage/google_keep_sync.your.email@domain.com.json
3. Add the integration again with a new token.

**Comment by supremelucifer** [comment] 2024-10-01 07:32
The weird part is, i generated a new token with my own credentials and even on different machines. A proxmox docker and a synology docker. Didnt try the [google_keep_sync.your.email@domain.com.json](mailto:google_keep_sync.your.email@domain.com.json) to so im gonna try that!

**Comment by watkins-matt** [comment] 2024-10-03 20:36
Closing this issue because it does not seem to be a reproducible bug.

**Closed by watkins-matt** 2024-10-03 20:36 UTC
